### ISSUE TITLE
Problem adding TXT record.

### ISSUE THREAD

**Issue by eminata** [exonet/powerdns-php#104]
## Detailed description

When I want to add a TXT record, the dot character added to the beginning of the domain name causes the process to terminate with an error.

## Possible implementation

When adding a TXT record, the domain name must not start with a dot character.

**Comment by trizz** [comment]
Hi @eminata,

As far as I know, a record can never start with a dot. This is not a limitation of this package, but it's the way how DNS works. If you think this is incorrect, please post the error you've received.

**Comment by eminata** [comment]
First of all, thank you for your help and sharing this library with us.

### Request Details Debug
Array
(
    [method] => PATCH
    [url] => http://dnsserverip:8081/api/v1/servers/localhost/zones/domain.com.
    [headers] => Array
        (
            [X-API-Key] => xapikey
            [Accept] => application/json
            [Content-Type] => application/json
            [User-Agent] => powerdns-php/v4.0.0
        )

    [payload] => {"rrsets":[{"name":".domain.com.","type":"TXT","ttl":3600,"changetype":"REPLACE","records":[{"content":"\"v=spf1 a ip4:78.1.2.0\/20 ~all\"","set-ptr":false,"disabled":false}]}]}
)
### Response
422 - Unprocessable Entity - Unable to parse DNS Name
### Code
https://github.com/exonet/powerdns-php/blob/master/src/Helper.php#L42
## Help
If I remove the dot at the beginning of the domain name, the operation is successful. If this is not an error, how should I proceed?
