### ISSUE TITLE
Incorrect payload key on record creation: set_ptr

### ISSUE THREAD

**Issue by tkald** [exonet/powerdns-php#12]
## Detailed description

On creating record entries, wrong payload key is used: "set_ptr", should be "set-ptr"

**Comment by tkald** [comment]
How do I actually get record added / deleted to / from domain with payload "set-ptr":true ?

**Comment by trizz** [comment]
It is currently not possible to filter the records with `set-ptr: true` from within this package or to get the created PTR record in the response (it is not returned by PowerDNS). 

However, you can 'search' in the zone for PTR records like this: `$zone->find('example', RecordType::PTR);` after you've added the record.

Also please note that according to [the PowerDNS docs](https://doc.powerdns.com/authoritative/http-api/zone.html#record), the `set-ptr` method is deprecated and will be removed in 4.3.
