### ISSUE TITLE
Delete metadata SOA-EDIT

### ISSUE THREAD

**Issue by lukasmedia** [exonet/powerdns-php#132]
### Short description
Every domain that is created has metadata; kind (content): API-RECTIFY (1), SOA-EDIT (NONE) and SOA-EDIT-API (DEFAULT).

The issue: my system administrator asked me to remove the SOA-EDIT records. Ofcourse i can do this using a query/mysql; but it would be nice if i could the use the API for this.

### Usecase
```
            $newZone = new ZoneResource();
            $newZone->setName($domain . '.');
            $newZone->setKind('master');
            $newZone->setNameservers($nameservers);
```

### Description

```
$newZone->setSoaEdit(); // no parameter deletes the record (?)
```

or just:

```
$newZone->delSoaEdit(); // 
```

[update]
The API supports this: https://doc.powerdns.com/authoritative/http-api/metadata.html

Many thanks, keep up the good work!

**Comment by trizz** [comment]
Hi @lukasmedia,

I just made a pull request to add the feature you asked for. The package should get an update this week or next with the new functionality.
