### ISSUE TITLE
Second (optional) argument of an Exception is its code, not debug variables

### ISSUE THREAD

**Issue by jeroenvermeulen** [exonet/powerdns-php#137]
Here is a bug:
https://github.com/exonet/powerdns-php/blob/cd6a66db6e60d65bd8138781ab1e51f7a636e58d/src/Resources/ResourceRecord.php#L375-L378

`Exonet\Powerdns\Exceptions\InvalidRecordType` extends `Exonet\Powerdns\Exceptions\PowerdnsException`, which extends `\Exception`.
The second argument should be the exception code, not an array with extra information.
See https://www.php.net/manual/en/class.exception.php

**Comment by trizz** [comment]
Thanks, this is indeed something that should be fixed. Somewhere in the upcoming week(s) I'll make time to fix this and the other outstanding issues.
