### ISSUE TITLE
MX-record priority?

### ISSUE THREAD

**Issue by XAKEPEHOK** [exonet/powerdns-php#17]
Is it possible to create MX-record with some priority by your library?

**Comment by trizz** [comment]
Hi @XAKEPEHOK,

Yes, as the priority is just part of the content. You can add an MX record with priority 10 like this:
`$zone->create('zone-name.com.', RecordType::MX, '10 mail.zone-name.com.');`

**Comment by XAKEPEHOK** [comment]
Thanks!
