### ISSUE TITLE
TTL values of nameservers defaulting to 3600

### ISSUE THREAD

**Issue by rodehoed** [exonet/powerdns-php#18]
## Detailed description
When adding an zone it seems that the TTL value of NS records is set to 3600.

## Context
Would be nice if we could add an TTL value too. For us 3600 it's a little bit low for me.

**Comment by trizz** [comment]
Unfortunately, when creating a zone it is only possible to send an array with strings for NS records. So you must update the TTL _after_ creating the zone, which can be done like this:

```php
use Exonet\Powerdns\RecordType;
use Exonet\Powerdns\Resources\ResourceRecord;

$zone->get(RecordType::NS)->map(function (ResourceRecord $record) {
    $record->setTtl(3600*5)->save();
});
```

**Comment by rodehoed** [comment]
And again, big thanks trizz!
