### ISSUE TITLE
Delete only 1 record from RR Set

### ISSUE THREAD

**Issue by rodehoed** [exonet/powerdns-php#19]
## Detailed description
I have some examples where I have multiple A records with the same name. eg:

- test1.zone.example.    IN A  127.0.0.1
- test1.zone.example.    IN A  127.0.0.2

PDNS will see this as Resource Record Set. And thus if I delete (with find) _test1_ both records are gone even if I want to have one left.

I'm aware that this is mainly PDNS behaviour, but any tip to handle this sort of cases?

Ohh and +1 for this project!

**Comment by trizz** [comment]
It is possible to change the records inside a resource record. The following example will remove the record where `127.0.0.1` is set as content:

```php
use Exonet\Powerdns\RecordType;
use Exonet\Powerdns\Resources\Record;
use Exonet\Powerdns\Resources\ResourceRecord;

$zone->find('test', RecordType::A)->map(function (ResourceRecord $resourceRecord) {
    // Get all records in the found resource records.
    $records = $resourceRecord->getRecords();

    // $records is just a plain array with Record instances. You can remove/add whatever you like.
    $updatedRecords = array_filter($records, function (Record $record) {
        return $record->getContent() !== '127.0.0.1';
    });

    // By calling 'setRecords' (plural!) all of the records will be replaced.
    $resourceRecord->setRecords($updatedRecords)->save();
});
```

**Comment by rodehoed** [comment]
Big thanks trizz!
