### ISSUE TITLE
Create new NS, MX with different TTL

### ISSUE THREAD

**Issue by wgjr** [exonet/powerdns-php#23]
Hello, thanks again for the class.

Is it possible to create NS, MX records with different TTL?
So how to update the TTL of a specific NS, MX?

**Comment by trizz** [comment]
Hi @wgjr,

For now there is no way to create a new zone with a different TTL for the NS records. However, you can update the TTL of an existing zone (or directly after creating it):

```php
$powerdns
    ->zone($domain)
    ->get(RecordType::NS) // Or: RecordType::MX for all MX records.
    ->map(function (ResourceRecord $resourceRecord) {
        $resourceRecord->setTtl(600)->save();
    });
```

This will update all records of the specified type with a TTL of 600. 

When creating new records in an existing zone, you can pass the TTL as 4th argument:
```php
$zone->create('test2', RecordType::A, '127.0.0.2', 3600);
```

**Comment by wgjr** [comment]
Thank you for your help
