### ISSUE TITLE
How to increment serial ?

### ISSUE THREAD

**Issue by mickaelmonsieur** [exonet/powerdns-php#24]
Hello,
I try to increment serial.

```
			$zone = $powerdns->zone("test.com");

			if(substr($zone->resource()->getSerial(), 0, 8) == date("Ymd")) {
				$serial = $zone->resource()->getSerial() + 1;
			}
			else {
				$serial = date("Ymd") . '00';
			}

			$zone->resource()->setSerial($serial);
```

why doesn't it work?
do you have another solution?

**Comment by trizz** [comment]
Hi @mickaelmonsieur,

Currently it is not possible to update the SOA serial yourself. 

However, it seems that you want to increase it, which will happen automatically when the zone has `INCEPTION-INCREMENT` configured as a value for `SOA-EDIT`. At this moment it is not possible to manage this with this package. You can use [pdnsutil](https://doc.powerdns.com/authoritative/manpages/pdnsutil.1.html) to check/update the meta of the zone.

**Comment by mickaelmonsieur** [comment]
Hi @trizz ,
I don't think letting powerdns increase the serial itself makes any sense.
I explain why:
If I add 250 entries in my zone, the server increases 250x the serial? It makes no sense.
I just have to update the serial at the end of all my modifications, don't you think?

**Comment by robbinjanssen** [comment]
Hi @mickaelmonsieur, thanks for your issue!

I think it is pdns own advice to update the serial after _each_ change, so therefor we sticked with the default. I like it cause I don't want to worry about the serial update :-) 

I'm afraid I don't see us implementing this any time soon, but we're absolutely open for a pull request!

To achieve this a `save()` method must be created in the [`Zone`](https://github.com/exonet/powerdns-php/blob/master/src/Zone.php) class. It should implement the [`put`](https://doc.powerdns.com/authoritative/http-api/zone.html#put--servers-server_id-zones-zone_id)  API call.

Let us know if we can be of any more help.
