### ISSUE TITLE
CNAME Record

### ISSUE THREAD

**Issue by wgjr** [exonet/powerdns-php#29]
Hello, again thanks for the code and I come to ask for help.

I'm having trouble creating CNAME records.

Apparently it is not in the correct format, but I cannot find the necessary format, could you help me with that?

Exonet \\ Powerdns \\ Exceptions \\ ValidationException: Record www.domain.net./CNAME 'domain.net': Not in expected format (parsed as 'domain.net.') in /home/public_html/vendor/exonet/powerdns-php/src/Connector.php:155\nStack

**Comment by trizz** [comment]
Hi @wgjr,

I understand the confusion in this case. The CNAME must have a canonical name as value, for example `domain.net.` - the last dot is important!

The validation error as returned from PowerDNS is a bit confusing. It states that the value is 'parsed as 'domain.net.'', but in reality, it isn't.

**Comment by trizz** [comment]
This issue has gone silent, closing for now. If you have any more questions feel free to reopen!
