### ISSUE TITLE
Fatal error by 'unknown' response status codes

### ISSUE THREAD

**Issue by davey-w** [exonet/powerdns-php#32]
I'm getting the following fatal error when the response returns a statuscode which is not 200,201,204 or 422:

`Uncaught Error: Wrong parameters for Exonet\Powerdns\Exceptions\PowerdnsException([string $message [, long $code [, Throwable $previous = NULL]]]) in xxxxxx/vendor/exonet/powerdns-php/src/Connector.php:161`

In my case, I'm getting a 403 statuscode which is causing this error. Shouldn't there be a default in the ` switch ($response->getStatusCode())` in the `parseResponse` method in Connector.php ? So in case we're getting a status code other than the 4 I mentioned before?

**Comment by trizz** [comment]
Hi @davey-w,

Thanks for reporting this problem! There is already a [default 'fallback'](https://github.com/exonet/powerdns-php/blob/f00d5c1c7086b49d9a68124628a363acddc86a32/src/Connector.php#L162) if the status code isn't 200, 201, 204 or 422. However, in your case the `$content` variable is null or not a string, which is [required as first exception parameter](https://www.php.net/manual/en/language.exceptions.extending.php).

I've just pushed a branch that will [fix this issue](https://github.com/exonet/powerdns-php/commit/f00d5c1c7086b49d9a68124628a363acddc86a32). Can you try it to see if this fixed your problem? You can use this branch by using composer: 
```bash
composer require exonet/powerdns-php:dev-tsi\/32-log-error
```

Please let me know if this fixes your error, so I can release it.

**Comment by davey-w** [comment]
@trizz Ah I understand! Yes, seems to fix the issue, thanks!

**Comment by trizz** [comment]
@davey-w Verion [2.3.1](https://github.com/exonet/powerdns-php/tree/v2.3.1) is tagged! Do not forget to update your `composer.json` again, the branch you're using will be deleted. Just `composer require exonet/powerdns-php` (without branch info) should suffice.
