### ISSUE TITLE
How to return status code in controller

### ISSUE THREAD

**Issue by matt-smartlabs** [exonet/powerdns-php#34]
Hi Guys,

I'm trying to create a function which will add a zone to the DNS server and if the zone has been added successfully I would like to add this information to the user's account, now to do that I will need to get a status code in the controller.

So when I'm for example adding a zone or a record

e.g:
`
$powerdns->createZone($domain, $nameServers)->create($dnsRecords);`

I'm looking to get some response like $powerdns['error'] => true or false or $powerdns->getStatusCode() => Conflict.

Currently when something will fail I'm getting exception but I don't know how I can process it in the controller.

Many thanks,
Matt

**Comment by trizz** [comment]
Hi Matt,

There is currently no way to access request data. However, when something goes wrong, a [ValidationException](https://github.com/exonet/powerdns-php/blob/master/src/Connector.php#L155) is returned when the validation fails. If something went wrong that is not a validation error, a more generic [PowerdnsException](https://github.com/exonet/powerdns-php/blob/master/src/Connector.php#L162) will be thrown. You are correct that you are getting an exception which [can be caught](https://www.php.net/manual/en/language.exceptions.php).

So, to answer your question you can catch one, or both, exceptions in your controller:

```php
public function myFancyControllerFuntion() {
    try {
        $powerdns->createZone($domain, $nameServers)->create($dnsRecords);
    } catch (\Exonet\Powerdns\Exceptions\ValidationException $validationException) {
        // The PowerDNS validation error is set as message on the exception:
        return myViewRender('dns-validation-error', ['error-message' => $validationException->getMessage()]);
    } catch (\Exonet\Powerdns\Exceptions\PowerdnsException $powerDnsException) {
        // The PowerDNS validation error is set as message on the exception:
        return myViewRender('dns-error', ['error-message' => $powerDnsException->getMessage()]);
    }

    return myViewRender('dns-success', 'DNS Zone was created!');
}
```

Or, if you just want a single catch block:
```php
public function myFancyControllerFuntion() {
    try {
        $powerdns->createZone($domain, $nameServers)->create($dnsRecords);
    } catch (\Exonet\Powerdns\Exceptions\PowerdnsException $powerDnsException) {
        // The ValidationException extends the PowerdnsException, so cachting the PowerdnsException will handle both exceptions.
        return myViewRender('dns-error', ['error-message' => $powerDnsException->getMessage()]);
    }

    return myViewRender('dns-success', 'DNS Zone was created!');
}
```

In this example I've used a fake function `myViewRender` but you can of course add any logic you'd like, such as setting variables or other data.

**Comment by matt-smartlabs** [comment]
@trizz Thank you very much for your help!! That's amazing it's working how I wanted :)
