### ISSUE TITLE
Why is the port 8001

### ISSUE THREAD

**Issue by SjamonDaal** [exonet/powerdns-php#36]
Hi, Why is the default port hardcoded to be 8001 and not 8081.
As the documentation of PowerDNS states the default webserver port is 8081.
https://doc.powerdns.com/authoritative/http-api/index.html#webserver

Also there is not documentation how to change the port.
When I try the following I get the error: Conflict.
```php
$powerdns = new Powerdns('127.0.0.1', 'powerdns_secret_string', 8081);
```

```
50: Exonet\Powerdns\Exceptions\PowerdnsException 
…/vendor/exonet/powerdns-php/src/Connector.php162
49: Exonet\Powerdns\Connector parseResponse
…/vendor/exonet/powerdns-php/src/Connector.php128
48: Exonet\Powerdns\Connector makeCall
…/vendor/exonet/powerdns-php/src/Connector.php63
47: Exonet\Powerdns\Connector post
…/vendor/exonet/powerdns-php/src/Powerdns.php146
46: Exonet\Powerdns\Powerdns createZone
…/app/Handlers/PowerDnsHandler.php26
```

**Comment by trizz** [comment]
Hi @SjamonDaal,

The default value is a leftover from an [incorrect part](https://github.com/PowerDNS/pdns/pull/7464) of the PowerDNS documentation when the package was initially created. Changing it is a breaking change (the default behavior is changed) so I can't change it now. In the next major release we will fix it, but we do not have a release date for it.

Concerning your error, specifying the port as third argument should work, so I guess something else goes wrong. Unfortunately, the provided data is a bit scarce. Can you post the related code that you use to create the zone?

**Comment by SjamonDaal** [comment]
I followed the instructions in the readme within my laravel project. I've decided already to code the handling for powerdns myself and it's working exactly how I like now so I don't use this project anymore. For that reason I'll close this issue now.
