### ISSUE TITLE
Exception if comments is null

### ISSUE THREAD

**Issue by OneHatRepo** [exonet/powerdns-php#38]
I'm getting the following exception thrown when calling $resourceRecord->getComments() and the value for $resourceRecord->comments is null:

`TypeError: Return value of Exonet\Powerdns\Resources\ResourceRecord::getComments() must be of the type array, null returned`

Perhaps $comments should be initialized to [] in ResourceRecord.php, line 29?

Or if that's not a good idea, then perhaps we could have a hasComments() method, so we can know when to call getComments()?

As it is right now, not even a try/catch block will suppress the exception.

**Comment by trizz** [comment]
Hi @OneHatRepo,

Valid point. I'll address this together with #35.
