### ISSUE TITLE
ResourceRecord::getZone() would be helpful

### ISSUE THREAD

**Issue by OneHatRepo** [exonet/powerdns-php#40]
The ResourceRecord class has getters and setters for all private variables except that it's missing a getter for zone. A getZone() method would be useful for me, as I'm having to pass these objects around, and in a context where I don't have immediate access to the zone. The zone record is there on the ResourceRecord class, but because it's private, I can't access it.

**Comment by trizz** [comment]
👍 I'll add a getter in the upcoming release.

**Comment by OneHatRepo** [comment]
Thanks!
