### ISSUE TITLE
How to delete a single record?

### ISSUE THREAD

**Issue by dandju** [exonet/powerdns-php#43]
Hi,

I was wondering how to delete a single, specific record from a zone? For example if I have multiple MX records and want to delete or update one?

The `$zone->find()` can be restricted to the name and record type, but not to the content, which would be the "unique identifier" for that specific record.

Thanks

**Comment by trizz** [comment]
Hi @dandju,

In the case of MX records it is important to know the difference between a RRSet (Resource Record Set) and a Record. The `find` method will return an RRSet in the form of the ResourceRecord class. One ResourceRecord can contain multiple records, so the ResourceRecord `MX mydomain.com` can contain two (or more) Records: `10 mail.mydomain.com.`, `20 mail2.mydomain.com.` etc.

Say for example that you'd like to remove `20 mail2.mydomain.com.` you need to update the records in the ResourceRecord class. This will look something like this (not tested):

```php
$resourceSets = $zone->find('mydomain.com', RecordType::MX);

foreach ($resourceSets as $resourceSet) {
    $records = $resourceSet->getRecords();
    
    // $records is a plain array consisting of Record classes for each record.
    // You can do with this array whatever you want. Add items, remove items, update items, etc.
    
    // After you've changed the array to your liking, you need to replace the existing ones:
    $resourceSet->setRecords($records);

    // And save the resource set:
    $resourceSet->save();
}
```

Again, I've not tested this, but it should push you in the right direction. If you've any further questions, please let me know.

**Comment by trizz** [comment]
This issue has gone silent, closing for now. If you have any more questions feel free to reopen!
