### ISSUE TITLE
Query for records/record sets without knowing the zone (add a search resource?)

### ISSUE THREAD

**Issue by geoff-maddock** [exonet/powerdns-php#51]
## Detailed description

As a developer I would like to query records by content and retrieve a list of records

## Context

I have an older app that connects to PDNS via the database, and we're looking to move to using the API.
Our app has a list page that lets the user filter all records by the record content, zone etc.

I don't see this in the PDNS api or this project - has anyone solved this problem?

## Possible implementation

Make use of the search endpoint in the API?

## Your environment

* Version used: PHP  7.4
* Operating system and version:  centos

**Comment by trizz** [comment]
Hi @geoff-maddock,

At this moment the search endpoint is not supported. However, I think this is a good addition for this package, so I'll add it to our planning for (one of) our next sprint(s). I guess this will be around January.

**Comment by robbinjanssen** [comment]
@geoff-maddock The search endpoint has been implemented in v2.6.0 :)
