### ISSUE TITLE
Filtering and paginating lists

### ISSUE THREAD

**Issue by geoff-maddock** [exonet/powerdns-php#52]
## Detailed description

As a user I would like to filter lists of zones and paginate results.

I didn't see such a feature in the API.

## Context

Why is this change important to you? How would you use it?

There is no search resource currently, so it would be nice to filter within a specific resource.
If there is a large result set, the request may time out.

## Possible implementation

Unknown - ideally leverage the underlying API

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* Version used: PHP 7.4
* Operating system and version: Unix Centos

**Comment by trizz** [comment]
Hi @geoff-maddock,

I've looked into this and unfortunately there's no reliable way of getting limited results of zones. Filtering or paginating inside the package is possible, but it does not prevent timeouts, as all zones still will be retrieved at once. So unless PowerDNS adds pagination to the API itself, it is not possible to get a paginated/filtered list of zones. I'll keep track of [this PowerDNS issue](https://github.com/PowerDNS/pdns/issues/5142) and once there's pagination, we'll add it right away to the package.

**Comment by geoff-maddock** [comment]
Thanks for the followup Tristan.  This is the first time our team has really looked into the API, so I wasn't completely aware of the limits of the API.   Do you have any documentation on how how you handle the filtering and pagination using your package?
It's possible we might be able to work with that if the retrieval times aren't too much.

We're exploring creating our own API using API platform for reads, but probably would only be for reads and filtering.

**Comment by trizz** [comment]
At this moment there's no such thing as filtering and pagination in the package, as there are no endpoints that support it. Getting a list of zones will always return all zones. If you do not want this, you'll need to create your own workaround, for example keeping a list of zones in your own DB which you can use. Unfortunately we can't do anything about it.
