### ISSUE TITLE
listZones could be faster

### ISSUE THREAD

**Issue by frankvanhest** [exonet/powerdns-php#60]
According to the PowerDNS documentation the listZones could be a lot faster. https://doc.powerdns.com/authoritative/http-api/zone.html#get--servers-server_id-zones
When providing the query parameter `dnssec=false` performance increase is for 12000 zones is a factor of 10.

I would be happy create a PR to include an argument for the listZones method to set the dnssec flag to false in the request to PowerDNS with a default true, so there won't be any BC breaking.

What is you thought about this?

**Comment by trizz** [comment]
Hi @frankvanhest,

Nice find! We'll gladly accept your PR with this change.

**Comment by frankvanhest** [comment]
Hey @trizz, 

Well here it is #61 ;)

**Comment by trizz** [comment]
Thanks! I've merged your PR and will tag a new release today.
