### ISSUE TITLE
Compatible with PowerDNS 4.4?

### ISSUE THREAD

**Issue by frankvanhest** [exonet/powerdns-php#66]
Good morning,

The title says it all. Is this package compatible with PowerDNS 4.4?

Cheers,

Frank van Hest

**Comment by trizz** [comment]
Hi @frankvanhest,

While we've not tested it yet with 4.4, I think there should be no problem using this package against PowerDNS 4.4. The [changelog](https://doc.powerdns.com/recursor/changelog/4.4.html) does not include any specific API changes.

We will add (and test) "official" support for 4.4 soon.

**Comment by frankvanhest** [comment]
Hi @trizz,

Thanks for your reply! I thought why not do it myself, but then I run into the problem that PowerDNS 4.4 is not yet available for  Docker https://registry.hub.docker.com/r/psitrax/powerdns.

A quick search did not result in an alternative one.

Hopefully you'll have better luck. Let me know if you find one or https://registry.hub.docker.com/r/psitrax/powerdns has 4.4 available. I'm happy to help you get the support for 4.4.

Cheers,

Frank
