### ISSUE TITLE
Multiple A records for the same hostname

### ISSUE THREAD

**Issue by dotsensei** [exonet/powerdns-php#67]
Hello,

How can I add multiple A records for the same hostname? And then update/delete them? I.e. test.example.com has IPs 1.2.3.4. I need to add same hostname, with IP 5.6.7.8. Then I need to modify 1.2.3.4 to 9.10.11.12

Is it possible?
I tried sometime ago using the examples, but ended having funny issues like deleting one record resulted in deletion of all A records with the same hostname. Now I need it again, and not sure from where to start? 

Thank you.

**Comment by robbinjanssen** [comment]
Hi @dotsensei, please read issue #65, if it still doesn't make any sense (which I can understand 😁), let me know!

**Comment by robbinjanssen** [comment]
I'm closing this issue, if you have anything is still unclear feel free to reopen the issue! 👍

**Comment by dotsensei** [comment]
I think most of it is clear, but what I don't get is - in the #65 example, I see how to use a resourceSet for NS records, and that I can use the same for my case - an A record with two different IPs.
You get the resource set via `$resourceSets = $zone->get(RecordType::A);`
But what if I also have another A records? 

www A 1.2.3.4
www A 5.6.7.8
something A 10.11.12.13

Would the record **something** be also in the resource set, or it would be accessible separately? Thank you!

**Comment by trizz** [comment]
The `get` method will return all records with that type, so both the `www` and `something`. If you want only `www` you can use the `find` method: `->find('www', RecordType::A);`.
