### ISSUE TITLE
Guzzle PSR7 released 2.0 which breaks this package

### ISSUE THREAD

**Issue by frankvanhest** [exonet/powerdns-php#75]
Guzzle release a new version of PSR7 which has removed `\GuzzleHttp\Psr7\stream_for` from the codebase.

## Detailed description

For a quick fix, lock `guzzlehttp/guzzle` on `7.2` in composer.json.

For a lasting fix, see what the replacement is for `\GuzzleHttp\Psr7\stream_for`.

## Context

Currently a composer update will break an application using this package.

## Your environment
Use PHP8 and run a composer update and try to make a call to PowerDNS API.

**Comment by robbinjanssen** [comment]
Also see https://github.com/guzzle/psr7#upgrading-from-function-api and https://github.com/guzzle/psr7/blob/master/src/Utils.php#L286

Seems like a quickfix :-)

**Comment by robbinjanssen** [comment]
Tagged! https://github.com/exonet/powerdns-php/releases/tag/v3.3.1
