### ISSUE TITLE
SearchResult fails on zone and comment results

### ISSUE THREAD

**Issue by arichard42** [exonet/powerdns-php#78]
## Detailed description

The SearchResult class fails to interpret zone and comment results and issues warnings :

PHP Notice:  Undefined index: content in /root/pdns-cli/vendor/exonet/powerdns-php/src/Resources/SearchResult.php on line 148
PHP Notice:  Undefined index: disabled in /root/pdns-cli/vendor/exonet/powerdns-php/src/Resources/SearchResult.php on line 149
PHP Notice:  Undefined index: ttl in /root/pdns-cli/vendor/exonet/powerdns-php/src/Resources/SearchResult.php on line 152
PHP Notice:  Undefined index: type in /root/pdns-cli/vendor/exonet/powerdns-php/src/Resources/SearchResult.php on line 153
PHP Notice:  Undefined index: zone in /root/pdns-cli/vendor/exonet/powerdns-php/src/Resources/SearchResult.php on line 154

during processing a zone result, and :

PHP Notice:  Undefined index: disabled in /root/pdns-cli/vendor/exonet/powerdns-php/src/Resources/SearchResult.php on line 149
PHP Notice:  Undefined index: ttl in /root/pdns-cli/vendor/exonet/powerdns-php/src/Resources/SearchResult.php on line 152

during processing a comment result.

This is a bug in public function setFromApiResponse(array $data) that tries to get record data that are not present on zone results or comment results. 

## Context

This is not well documented in the powerdns REST API documentation, but depending on the SearchResult type, depending on the returned object type the SearchResult contains theses properties :

object_type = "record", properties returned = content, disabled, name, object_type, zone_id, zone, type, ttl
object_type = "comment", properties returned = content, name, object_type, zone_id, zone, type (no disabled or ttl fields)
object_type = "zone", properties returned = name, object_type, zone_id  (no content, disabled, zone, type or ttl fields) 

## Possible implementation

A simple change to overcome this problem is to replace :

    public function setFromApiResponse(array $data): self
    {
        $this->content = $data['content'];
        $this->disabled = (bool) $data['disabled'];
        $this->name = $data['name'];
        $this->objectType = $data['object_type'];
        $this->ttl = (int) $data['ttl'];
        $this->type = $data['type'];
        $this->zone = $data['zone'];
        $this->zoneId = $data['zone_id'];

        return $this;
    }

with

    public function setFromApiResponse(array $data): self
    {
        $this->content = isset($data['content']) ? $data['content'] : null;
        $this->disabled = isset($data['disabled']) ? (bool) $data['disabled'] : null;
        $this->name = $data['name'];
        $this->objectType = $data['object_type'];
        $this->ttl = isset($data['ttl']) ? (int) $data['ttl'] : null;
        $this->type = isset($data['type']) ? $data['type'] : null;
        $this->zone = isset($data['zone']) ? $data['zone'] : null;
        $this->zoneId = $data['zone_id'];

        return $this;
    }

in exonet/powerdns-php/src/Resources/SearchResult.php

## Your environment

The problem was hit using linux centos-8, php 7.2.24, pdns 4.5.1.

**Comment by trizz** [comment]
Hi @arichard42,

I've fixed this in the upcoming release! Thanks!
