### ISSUE TITLE
Question: `put` a full array of rrset changes to zone

### ISSUE THREAD

**Issue by lucasRolff** [exonet/powerdns-php#83]
## Detailed description

I'm trying to find a way in the powerdns client (Thanks for an awesome module by the way!) to update/replace a bunch of records in one fly (different record types).

My array format is exactly the same as in the `new_domain_from_zone_resource.php` example:
```php
$deletedDnsRecords = [
    ['name' => 'subdomain', 'type' => RecordType::A, 'content' => '127.0.0.1', 'ttl' => 60],
    ['name' => 'subdomain', 'type' => RecordType::AAAA, 'content' => '2a00:1e28:3:1629::1', 'ttl' => 60],
    ['name' => 'www', 'type' => RecordType::CNAME, 'content' => 'google.com.', 'ttl' => 60],
];
$addedDnsRecords = [
    ['name' => 'subdomain', 'type' => RecordType::A, 'content' => '10.0.0.1', 'ttl' => 60],
    ['name' => 'www', 'type' => RecordType::A, 'content' => '127.0.0.1', 'ttl' => 60],
    ['name' => 'www', 'type' => RecordType::AAAA, 'content' => '2a00:1e28:3:1629::1', 'ttl' => 60],
];
```

I have a zone editor in a webpage, where the whole zone is loaded in from PowerDNS using this package.
When I click "Save zone", I calculate the difference between the "original" zone, and the updated one (coming in via a `POST` request).

To do this, I use two simple `array_filter` functions (This is the only way I know how to "compare" multidimensional arrays).

```php
        $addedRecords = array_filter($newDnsRecords, function($element) use ($oldDnsRecords) {
            return !in_array($element, $oldDnsRecords);
        });


        $deletedRecords = array_filter($oldDnsRecords, function($element) use ($newDnsRecords) {
            return !in_array($element, $newDnsRecords);
        });
```

In the above case, I have e.g. changed `subdomain` from IP `127.0.0.1` to `10.0.0.1`, as well as changed `www` from a `CNAME` to `A` and `AAAA` records.

What I'd love to do is to make a staged change that isn't committed, that does the following:
```php
foreach($deletedRecords as $record) {
    $zone->find($record['name'], $record['type'])->delete();
}

foreach($addedRecords as $record) {
    // Somehow if I pass $record directly, I get `Cannot access offset of type string on string`.
    $currentZone->create($record['name'], $record['type'], array_unique($record['content']), $item['ttl']);
}

// Now commit the changes!
```

Currently if I do the two `foreach`, then obviously records will disappear from PowerDNS (and return `NXDOMAIN`) until they're added back again (in the next loop) - so a way to do the changes locally on a Zone object, and then when I've done the changes I do, I send a single `save/commit` call.

Whether that's even possible in PowerDNS's own API, I don't know :( 

What I do know, is that when changing from A to CNAME or CNAME to A, I cannot just do a `$currentZone->create()` with e.g. a change from A to CNAME, since it will give a conflict exception.

I'm curious how other people handles a case like this, where you have to change/update batches, and go from one type to another - is the solution simply to e.g. delete the `CNAME` and then do another call shortly after to add the `A` record? Is there no way one can actually "replace" the RRset when changing to a different type?

## Context

To push bigger changes (e.g. loading in zone templates), replacing "replacing" all the content in a zone is desirable.

## Your environment

- PHP 8.0 on MacOS and Linux.

**Comment by lucasRolff** [comment]
I did add a bunch more information to the issue, which is why it has been updated a few times ^_^ sorry for not doing it properly first!

**Comment by trizz** [comment]
Hi @lucasRolff,

Your issue exists in fact of two parts, I'll try to answer them both.

> go from one type to another - is the solution simply to e.g. delete the CNAME and then do another call shortly after to add the A record? Is there no way one can actually "replace" the RRset when changing to a different type?

Yes, while it seems inefficient, this is also exactly how PowerDNS handles any change. Even if you change the name or TTL, it removes its old record in the database and inserts a new one, no 'real' update is performed. In PowerDNS [there's no real update method](https://github.com/exonet/powerdns-php/blob/master/examples/manage_records.php#L31-L36).

That said, with the knowledge of above example (and its comment) it is possible to do some kind of bulk actions, which is the second part of your issue/question.

By creating an array of resource records yourself, you can easily change the `change type` [from `REPLACE` to `DELETE`](https://github.com/exonet/powerdns-php/blob/master/src/Resources/ResourceRecord.php#L15-L23):
```php

$oldDnsRecords = [
    ['name' => 'subdomain', 'type' => RecordType::A, 'content' => '127.0.0.1', 'ttl' => 60],
    ['name' => 'subdomain', 'type' => RecordType::AAAA, 'content' => '2a00:1e28:3:1629::1', 'ttl' => 60],
    ['name' => 'www', 'type' => RecordType::CNAME, 'content' => 'google.com.', 'ttl' => 60],
    // I've added this one as a 'remove' record, as it is not set in the $newDnsRecords array.
    ['name' => 'removed', 'type' => RecordType::CNAME, 'content' => 'google.com.', 'ttl' => 60],
];
$newDnsRecords = [
    ['name' => 'subdomain', 'type' => RecordType::A, 'content' => '10.0.0.1', 'ttl' => 60],
    ['name' => 'www', 'type' => RecordType::A, 'content' => '127.0.0.1', 'ttl' => 60],
    ['name' => 'www', 'type' => RecordType::AAAA, 'content' => '2a00:1e28:3:1629::1', 'ttl' => 60],
    // I've added this one as a 'new' record, as it is not set in the $oldDnsRecords array.
    ['name' => 'new', 'type' => RecordType::AAAA, 'content' => '2a00:1e28:3:1629::1', 'ttl' => 60],
];

// For this example, create a new zone with the defined OLD records and name servers.
$zone = $powerdns->createZone($domain, $nameServers);
$zone->create($oldDnsRecords);

// Get an array with records that are deleted.
$deletedRecords = array_filter($oldDnsRecords, function($element) use ($newDnsRecords) {
    // Try to find the old record in the new record array.
    $recordIndex = array_search($element['name'], array_column($newDnsRecords, 'name'), true);

    if ($recordIndex === false) {
        // The record is deleted if nothing with the same name is found.
        return true;
    }

    // If the name or type are not the same, it is a different record.
    return $element['name'] !== $newDnsRecords[$recordIndex]['name'] || $element['type'] !== $newDnsRecords[$recordIndex]['type'];
});

// Create resource records for all deleted records.
foreach ($deletedRecords as $record) {
    $records[] = (new \Exonet\Powerdns\Resources\ResourceRecord())
        ->setName($record['name'].'.'.$zone->getCanonicalName())
        ->setType($record['type'])
        ->setTtl($record['ttl'])
        ->setRecord(new \Exonet\Powerdns\Resources\Record($record['content']))
        // And make sure that the change type is set to 'DELETE'.
        ->setChangeType('DELETE');
}

// Create resource records for all deleted records.
foreach ($newDnsRecords as $record) {
    $records[] = (new \Exonet\Powerdns\Resources\ResourceRecord())
        ->setName($record['name'].'.'.$zone->getCanonicalName())
        ->setType($record['type'])
        ->setTtl($record['ttl'])
        ->setRecord(new \Exonet\Powerdns\Resources\Record($record['content']))
        // And make sure that the change type is set to 'REPLACE' (default).
        ->setChangeType('REPLACE');
}

// Send the array with resource records as a PATCH to the zone.
$zone->patch($records);

// Output a list of records to see the changes.
$zone->get()->map(function (ResourceRecord $resourceRecord) {
    print_r($resourceRecord->getType()."\t");
    print_r($resourceRecord->getName()."\t");
    print_r($resourceRecord->getRecords()[0]->getContent());
    echo PHP_EOL;
});
```

There are several important things in this example:
- There's no need to create a separate 'new' records array. Because the name + type is the unique combination, it either will be created or updated when using the 'REPLACE' change type.
- The `deletedRecords` array now has the records where the combination of name + type is not present in the 'newDnsRecords' array. By setting the change type to 'DELETE' we instruct PowerDNS to remove all records with this name/type combination.
- By sending a PATCH to the zone, all the provided RRSets are updated/created/deleted.

The expected output of this example will be 2 A records (`www` and `subdomain`) and two AAAA records (`www` and `new`). The CNAME records should be removed (for `old`) and "updated" for `www`. Which in fact was a 'remove' and 'create'.

**Comment by lucasRolff** [comment]
Thanks @trizz! I'll try it when I get home from my first holiday in two years! Thanks for providing an awesome reply!
