### ISSUE TITLE
Hardcoded PDNS port

### ISSUE THREAD

**Issue by ponasromas** [exonet/powerdns-php#84]
Latest PDNS release 4.6 have web server on 8081 by default. Your lib hardcoded this for 8001. And better documentation would be appreciated ;) , fantastic library!

**Comment by robbinjanssen** [comment]
Hi @ponasromas, see https://github.com/exonet/powerdns-php/issues/36#issuecomment-643988520 for an explanation as of why this is the default port. Unfortunately changing it would result in a breaking change for this library, we might do this in the future but for now you can provide the port when constructing the [`Powerdns instance`](https://github.com/exonet/powerdns-php/blob/master/src/Powerdns.php#L67) :-)

I understand the lack of documentation, take a look at the [examples](https://github.com/exonet/powerdns-php/tree/master/examples), they might offer a better view of what/how you can achieve certain things.

**Comment by trizz** [comment]
Fixed in [version 4.0.0](https://github.com/exonet/powerdns-php/releases/tag/v4.0.0).
