### ISSUE TITLE
More human readable output

### ISSUE THREAD

**Issue by ponasromas** [exonet/powerdns-php#86]
Is it possible to obtain zone records in more human readable format? Current result set is returned is so complex to parse and understand... Example:

Current version:

```
foreach ($zoneResourceSets as $resourceSet) {
    $recordContents = array_map(function (Record $record) {
        return $record->getContent();
    }, $resourceSet->getRecords());

    echo sprintf(
        '| %-4s | %30s --> %-30s%s',
        $resourceSet->getType(),
        $resourceSet->getName(),
        implode(', ', $recordContents),
        PHP_EOL
    );
}
```

Suggestion:

```
foreach ($zoneResourceSets as $resourceSet) {

        echo $resourceSet->getARecords();
        echo $resourceSet->getMXRecords();
}
```

All that "sprintf" magic is insanely complex. I would like to see JSON output rather than array objects.

This is not a problem, rather a suggestion to improve library to be more user friendly and easy to use for non hardcore PHP users.

**Comment by robbinjanssen** [comment]
Hi @ponasromas,

I don't really understand your question here.

If you want JSON formatted data I'd suggest using the actual [PowerDNS API](https://doc.powerdns.com/authoritative/http-api/index.html#built-in-webserver-and-http-api) as this outputs JSON already.

This library provides an abstraction layer over the JSON API that powerdns exposes. It defines classes based on the fetched resource set with several methods (like `getType()`, `getName()` etc.).

The `sprintf` part is a basic PHP method that we use to format the example output. 
Try executing the code **without** sprintf:
```php
echo "Type: " . $resourceSet->getType() . " - Name: " . $resourceSet->getName() . " - Content: " . implode(', ', $recordContents) . "\n";
```

Can you try and explain what you are trying to achieve? :-)

**Comment by ponasromas** [comment]
I'am trying to make your library work in web hosting billing panel that I make. I'am creating PowerDNS module at the moment. It will allow clients to add zones from the panel and manage them. For that reason I'am looking for easy to use PHP library which works with PowerDNS.

Probably I need more examples :) 

BTW,  is there any method which could increment SOA and send "notify" about zone changes? Looking at older issues, I found one similar question, maybe it is available in current version?

**Comment by robbinjanssen** [comment]
Cool, that's definitely something you can achieve with this library. 

Incrementing the SOA is not necessary (and possible using the API), this is something handled by PowerDNS depending on your [configuration](https://doc.powerdns.com/authoritative/domainmetadata.html#soa-edit-api). 

By default this package uses the [`INCEPTION-INCREMENT`](https://doc.powerdns.com/authoritative/dnssec/operational.html#inception-increment) value when a new zone is created. 
 To supply another value checkout this [example](https://github.com/exonet/powerdns-php/blob/master/examples/new_domain_from_zone_resource.php#L42)

You can "notify" using the zone `notify` method (`$powerdns->zone($domain)->notify();`)

**Comment by ponasromas** [comment]
Robbin, your are gold! I will ask you for some help :)

Playing with example "list_records_for_zone.php", now, how I get content for each record type?

Because now, example gives me this result:

```
Type: TXT | Name: domain.tld.
Type: MX | Name: domain.tld.
```
But I have 2 MX records. How to extract those contents?

There is this construct:

```
    $recordContents = array_map(function (Record $record) {
        return $record->getContent();
    }, $resourceSet->getRecords());
```

It is returning desired record content:

```
"v=spf1 a mx include:_spf.example.com ?all"
2a00:1e28:3:1629::1
```
I need to display data like this:

Type: TXT | Name: domain.tld. | Content: "v=spf1 a mx include:_spf.example.com ?all"
Type: MX - domain.tld. | 2a00:1e28:3:1629::1

Also, I would like to access more fields, like prio, domain_id. Is it possible in library?

**Comment by robbinjanssen** [comment]
@ponasromas Maybe this is not the the right library for what you are trying to achieve and how you are trying to achieve it. Fields like "domain_id" are not exposed by the powerdns API. It works with zone names as identifiers.

PowerDNS works with Resource Record sets and a resource record set can contain multiple "records" with content for the same type and name. The prio is included in the "content" of MX records (and other types). It is not a separate field.

If you would like to directly edit all the data my suggestion is to use a MySQL connection to the PowerDNS database and use queries to update the values directly :) Make sure you validate the data though.

> I need to display data like this:

`$recordContents` is now an "array" filled with content, you can transform the array into a string by using `implode` for example.

As this is not an issue with the library but more of a general php question, im closing this issue.
