### ISSUE TITLE
cURL error 28: Failed to connect to xxx.xxxxx.xxx port 8081: Connection timed out

### ISSUE THREAD

**Issue by lukasmedia** [exonet/powerdns-php#92]
I'm updating and inserting about ~200 domains using a PHP script (Laravel) which is using a queue to insert/update at powerdns. After a few domains i get a curl timeout.

PHP/Laravel/Redis Queue/Ubuntu/PHP74 and PHP8.

**Comment by trizz** [comment]
Hi @lukasmedia,

This has probably nothing to do with the package, as a connection timeout usually indicates there's something amiss in the connection or on the server side, for example a firewall or something that limits the number of (simultaneous) connections.
